### ISSUE TITLE
Migrate hbbft1 testnet spec generation to the hbbft-posdao-contracts repository

### ISSUE THREAD

**Issue by dforsten** [artis-eco/openethereum#4]
For the hbbft1 testnet we implemented spec generation with the help of the hbbft_config_generator in the openethereum repo, which provides the threshold encryption keys required for the Honey Badger BFT genesis block.

These adaptations need to be migrated to the new, hbbft-specific POSDAO contracts repository.

**Comment by SurfingNerd** [comment]
Taken over from https://github.com/DMDcoin/openethereum/issues/2
