### ISSUE TITLE
Deploy new spec generated by hbbft-posdao-contracts to the Unit Test enviornment in openethereum

### ISSUE THREAD

**Issue by dforsten** [artis-eco/openethereum#5]
OpenEthereum Unit Tests use specs and contract JSON ABIs checked in to the OpenEthereum repository.

We need to add the new spec generated from the hbbft-posdao-contracts repository along with the JSON ABIs for these contracts to the repo to be avialable in Unit Tests.

**Comment by SurfingNerd** [comment]
Taken over as https://github.com/DMDcoin/openethereum/issues/3
